<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ExeScope.GUI</RootNamespace>
    <LangVersion>12.0</LangVersion>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest Condition="'$(OS)' == 'Windows_NT'">app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <PackageReference Include="Semi.Avalonia" Version="11.2.1.10" />
    <PackageReference Include="Semi.Avalonia.DataGrid" Version="11.2.1.10" />
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Google.Protobuf" Version="3.28.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExeScope.Contracts\ExeScope.Contracts.csproj" />
    <ProjectReference Include="..\ExeScope.Core\ExeScope.Core.csproj" />
  </ItemGroup>

</Project>
